#28 fix, #45 added option, small enhacements.
admesh/admesh pull request #47
Opened 2022-03-21 22:27 UTC by andreondra

Not sure with the #45 fix, I added a non-zero return value to stl_open if there is any syntax error (even recoverable) in the file. Maybe there are more things to check for validity but that requires additional format specifiaction.

2022-03-22 06:06 UTC, gladk commented
Thanks for your contribution. Please fix update the title of the PR to be used it in the release notes (what option added, what imprivements).

Could you please also add two stl-files: broken one and fixed one? I will add some basic tests to make a cross-check. Thanks

2022-03-22 07:42 UTC, hroncok requested changes
If I understand the status quo correctly, admesh will already fail when it encounters `stl->error`, or at least it *should* do that even without a new flag.

The flag should make admesh fail when the mesh was changed by admesh's repairing ability, not when there is an IO error.

2022-03-22 07:44 UTC, hroncok commented
@gladk JFYI @andreondra is a student at [FIT CTU  :lion:  :czech_republic:](https://fit.cvut.cz/en) doing this for extra credit and I'd like to ask you not to merge any PRs submitted by them before my approval (feel free to submit feedback and review, just don't merge). Thanks.

2022-03-22 07:47 UTC, hroncok commented
```
$ touch invalid.stl
$ admesh invalid.stl 
ADMesh version 0.98.4, Copyright (C) 1995, 1996 Anthony D. Martin
ADMesh comes with NO WARRANTY.  This is free software, and you are welcome to
redistribute it under certain conditions.  See the file COPYING for details.
Opening invalid.stl
The input is an empty file: Success
$ echo $?
1
```

While the `Success` message is confusing (and probably an error of an incorrect perror usage), the failure already happens.

2022-03-22 07:51 UTC, gladk commented
> @gladk JFYI @andreondra is a student at [FIT CTU lion czech_republic](https://fit.cvut.cz/en) doing this for extra credit and I'd like to ask you not to merge any PRs submitted by them before my approval (feel free to submit feedback and review, just don't merge). Thanks.

Sure! I would then propose to add some basic tests.

2022-03-23 20:13 UTC, andreondra commented
The #45 fix would need further discussion. I asked @hroncok via mail and he suggested the return code should be non-zero when any of the following values is different from zero:
```
Facets with 1 disconnected edge  :     0
Facets with 2 disconnected edges :     0
Facets with 3 disconnected edges :     0
Total disconnected facets        :     0 
Degenerate facets     :     0
Edges fixed           :     0
Facets removed        :     0
Facets added          :     0
Facets reversed       :     0
Backwards edges       :     0
Normals fixed         :     0
```
If I understand correctly, we should check final number of facets (`stl->stats.number_of_facets` etc.), not the original count (to signal the repair was not successful?). Also, we probably do not want to report non-zero if the user explicitly requested facet reversal (via `--reverse-all`).

2022-04-15 18:40 UTC, hroncok commented
Could you please split this to multiple separate PRs? It would be easier to review that way. Thanks.

2022-04-15 19:33 UTC, gladk commented
If it is really heap buffer overflow, do we need a CVE probably?

2022-04-15 19:53 UTC, andreondra commented
I split the relevant fixes into multiple PRs as @hroncok wanted, so I'm closing this PR. @gladk We can continue the discussion in a relevant PR: #55.

2022-04-15 19:53 UTC, closed without merging